// DEMO
export const UPDATE_DATA = 'UPDATE_DATA';

// Navigation
export const NAVIGATION_CHANGE_PAGE_INDEX = 'NAVIGATION_CHANGE_PAGE_INDEX';
export const NAVIGATION_SIDEBAR_UPDATE_ACTIVE = 'NAVIGATION_SIDEBAR_UPDATE_ACTIVE';
export const NAVIGATION_BOTTOMBAR_UPDATE_ACTIVE = 'NAVIGATION_BOTTOMBAR_UPDATE_ACTIVE';
